### ISSUE TITLE
The second bonus of v9 will have 4 loops instead of 2

### ISSUE THREAD

**Issue by DarkReaper231** [oxtaa/incredibox#1]
How do you plan dealing with this? When the second bonus comes out, it will have 4 loops instead of 2 like the first one has, this is something that we haven't seen yet in other versions so how are you gonna deal with that? WIll you deobf the code and see how they do it and retrofit the old code? 

If you will I have a tool that can deobfuscate partially the new code:
https://deobfuscate.relative.im/

It won't retrieve the correct variable names and values but it will at least make the code somewhat readable so you might be able to pinpoint where does it do this logic and retrofit the old code.

I still think the base should stay on the older version since it is not obfuscated

**Comment by oxtaa** [comment]
Just made an update adding v9 bonus 2! But I used the files extracted from the PC version that I bought some time ago, so it's not built over the old version anymore.

**Comment by DarkReaper231** [comment]
> Just made an update adding v9 bonus 2! But I used the files extracted from the PC version that I bought some time ago, so it's not built over the old version anymore.

I have a repository myself and I prefer the old version so I'll try modifying the code

**Comment by DarkReaper231** [comment]
@oxtaa I managed to implement dirty hack to the old code base btw
```js
            var bonusCode = [1, 2, 3, 16, 20]
            customLoopBonus = app.nbloopbonus
            if (JSON.stringify(D) === JSON.stringify(bonusCode)) {
                customLoopBonus = 4
            }
```
From now on I'll simply introduce other bonus codes with different loop durations. I prefer using the old 0.5.4 code because this way I not feel that guilty about having it on Github.

**Comment by oxtaa** [comment]
Wow, I actually tried to do that, but it seemed impossible, because it didn't work in testing.

**Comment by oxtaa** [comment]
Now i'll go back to the old version

**Comment by DarkReaper231** [comment]
> Now i'll go back to the old version

Okay in main.min.js add this variable
![image](https://github.com/oxtaa/incredibox/assets/38611351/c43f0e5f-94dd-4463-a49d-6476748e6628)
`customLoopBonus = 0,`

Then you need to go to this line 
`d.play(), m = !1, f = !0, h = !1, d.currentTime = S, r.addClass("playing"), a.hideLoader(), M.start(loopDuration * app.nbloopbonus, !1), v.prepare(g), v.play(S), p.addClass("show")`
here you add this code above the line
```js
var bonusCode = [1, 2, 3, 16, 20]
customLoopBonus = app.nbloopbonus
if (JSON.stringify(D) === JSON.stringify(bonusCode)) {
    customLoopBonus = 4
}
```
and then just replace `app.nbloopbonus` in the line to this `customLoopBonus`

And the last thing you need to do is go to `function playBonus()` which has this line
`modeReplay && (e = !!replayMix.waitForReloop || e), e && !bonusPlaying && (launchBonusVideo(), hidePoloLoader()), bonusPlaying && (++cntBoucleBonus == nbLoopBonus && waitForSlideUp(), cntBoucleBonus > nbLoopBonus && (checkUnlockNextBonus(), stopBonusVideo()))`
and just replace both occurances of `nbLoopBonus` to `customLoopBonus`

Leave the rest of the code same

**Comment by DarkReaper231** [comment]
When you need to add more custom bonus loops, you just add something like `bonusCode2` and add another check

**Comment by DarkReaper231** [comment]
Also if you want the web app working on Safari, you need to switch to mp3/mp4 from ogg/webm and set these variables accordingly
```
    sndtype = "mp3",
    vidtype = "mp4",
```
otherwise Safari users will receive errors because Safari doesn't support ogg and webm codecs

**Comment by oxtaa** [comment]
> > Now i'll go back to the old version
> 
> Okay in main.min.js add this variable ![image](https://private-user-images.githubusercontent.com/38611351/292530212-c43f0e5f-94dd-4463-a49d-6476748e6628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjc0MjQsIm5iZiI6MTcwMzI2NzEyNCwicGF0aCI6Ii8zODYxMTM1MS8yOTI1MzAyMTItYzQzZjBlNWYtOTRkZC00NDYzLWE0OWQtNjQ3Njc0OGU2NjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE3NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YTY1NWQxYzM3ZjE2MmYzMzdiYjI0MzNkZTIyZDc0MjFhNmRmNzZjN2Q3YmM0YzU0YTgzYTNlMjJjZWEzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GihLs6wYjgpN8EW1nW3OPvau1xQ7bMqzjhn1mcytghM) `customLoopBonus = 0,`
> 
> Then you need to go to this line `d.play(), m = !1, f = !0, h = !1, d.currentTime = S, r.addClass("playing"), a.hideLoader(), M.start(loopDuration * app.nbloopbonus, !1), v.prepare(g), v.play(S), p.addClass("show")` here you add this code above the line
> 
> ```js
> var bonusCode = [1, 2, 3, 16, 20]
> customLoopBonus = app.nbloopbonus
> if (JSON.stringify(D) === JSON.stringify(bonusCode)) {
>     customLoopBonus = 4
> }
> ```
> 
> and then just replace `app.nbloopbonus` in the line to this `customLoopBonus`
> 
> And the last thing you need to do is go to `function playBonus()` which has this line `modeReplay && (e = !!replayMix.waitForReloop || e), e && !bonusPlaying && (launchBonusVideo(), hidePoloLoader()), bonusPlaying && (++cntBoucleBonus == nbLoopBonus && waitForSlideUp(), cntBoucleBonus > nbLoopBonus && (checkUnlockNextBonus(), stopBonusVideo()))` and just replace both occurances of `nbLoopBonus` to `customLoopBonus`
> 
> Leave the rest of the code same

hm, seems like it's not working

**Comment by DarkReaper231** [comment]
@oxtaa What isn't working exactly?

**Comment by oxtaa** [comment]
@DarkReaper231 when I start the v9 bonus 2, it only lasts 2 loops, not 4.

**Comment by DarkReaper231** [comment]
> @DarkReaper231 when I start the v9 bonus 2, it only lasts 2 loops, not 4. I already modified main.min.js

Let me check on my end, give me few minutes

**Comment by DarkReaper231** [comment]
@oxtaa Okay first of all, your variable for codes is not D but C, so just change this if statement from `if (JSON.stringify(D)` to `if (JSON.stringify(C)`, replace D with C.

Btw did you get index.min.js from me? You shouldn't mix up different versions of the javascript. Your main.min.js variables are called differently meaning it was randomized in different way so you should supply your index.min.js

When you're at that find this line `d.play(), h = !1, f = !0, m = !1, d.currentTime = S, r.addClass("playing"), s.hideLoader(), B.start(loopDuration * app.nbloopbonus, !1), v.prepare(x), v.play(S), l.addClass("show")` and rename `app.nbloopbonus` to `customLoopBonus` and add this code above that line
```js
var bonusCode = [1, 2, 3, 16, 20];
var customLoopBonus = app.nbloopbonus
if (JSON.stringify(k) === JSON.stringify(bonusCode)) {
     customLoopBonus = 4;
}
```
keep in mind that in index script we don't need global customLoopBonus since it is only used here, the `playBonus` function is not present in index script so just declare customLoopBonus as local var as I did in the code block

**Comment by DarkReaper231** [comment]
Btw since when is 0.7.0 unobfuscated? I thought the last unobfuscated version is 0.5.4

**Comment by oxtaa** [comment]
> Btw since when is 0.7.0 unobfuscated? I thought the last unobfuscated version is 0.5.4, or are you using older code and just renamed it to 0.7.0?

i renamed it, but now i changed it to "v0.5.7 \<date>, modified \<date> by oxtaa"

**Comment by DarkReaper231** [comment]
> > Btw since when is 0.7.0 unobfuscated? I thought the last unobfuscated version is 0.5.4, or are you using older code and just renamed it to 0.7.0?
> 
> i renamed it, but now i've changed it to "v0.5.7 <date>, modified <date> by oxtaa"

Wait you use 0.5.7? There is a version of the app where 0.5.7 is not obfuscated? Because last time I checked, 0.5.7 was obfuscated already.

**Comment by oxtaa** [comment]
> > > Btw since when is 0.7.0 unobfuscated? I thought the last unobfuscated version is 0.5.4, or are you using older code and just renamed it to 0.7.0?
> > 
> > i renamed it, but now i've changed it to "v0.5.7 <date>, modified <date> by oxtaa"
> 
> Wait you use 0.5.7? There is a version of the app where 0.5.7 is not obfuscated? Because last time I checked, 0.5.7 was obfuscated already.

nah, it's not obfuscated, I used 0.5.7 since I started this project
